name: Docs Check

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd
        with:
          globs: |
            **/*.md
            !**/node_modules/**
          config: .markdownlint.json

  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411
        with:
          args: --no-progress --verbose './**/*.md'
          failIfEmpty: false
